name: first workflow 
on: workflow_dispatch
jobs:
     first_job: 
      runs-on: ubuntu-latest
      steps: 
         - name: print greeting
           run: mkdir satya
         - name: print goodbye
           run: cd satya
         - name: new job
           run: touch my name is satya

